from app.config.database import Base
from sqlalchemy import Column, ForeignKey, Integer, Float, DateTime
from sqlalchemy.orm import relationship

class DailyBlocks(Base):

    __tablename__ = "daily_blocks"

    id = Column(Integer, primary_key=True, index=True)
    company_id = Column(Integer)
    station_id = Column(Integer)
    fuel_grade_id  = Column(Integer)
    tank_id = Column(Integer)
    start_time = Column(DateTime)
    end_time = Column(DateTime)
    reporting_day = Column(DateTime)
    delivered_volume = Column(Float)
    delivered_cost = Column(Float)
    fuel_level = Column(Float)
    fifo_blended_cost = Column(Float)
    total_count  = Column(Integer)
    total_volume = Column(Float)
    total_sales_inc_vat = Column(Float)
    total_sales_ex_vat = Column(Float)
    total_net_margin_cost = Column(Float)
    total_bunker_commission = Column(Float)
    total_fixed_margin_adj = Column(Float)
    fuel_card_count = Column(Integer)
    fuel_card_volume = Column(Float)
    fuel_card_sales_inc_vat = Column(Float)
    fuel_card_sales_ex_vat = Column(Float)
    fuel_card_net_margin_cost = Column(Float)
    fuel_card_bunker_commission = Column(Float)
    fuel_card_fixed_margin_adj = Column(Float)
    bunkered_count = Column(Integer)
    bunkered_volume = Column(Float)
    bunkered_sales_inc_vat = Column(Float)
    bunkered_sales_ex_vat = Column(Float)
    bunkered_net_margin_cost = Column(Float)
    bunkered_bunker_commission = Column(Float)
    bunkered_fixed_margin_adj = Column(Float)
    retail_count = Column(Integer)
    retail_volume = Column(Float)
    retail_sales_inc_vat = Column(Float)
    retail_sales_ex_vat = Column(Float)
    retail_net_margin_cost = Column(Float)
    retail_bunker_commission = Column(Float)
    retail_fixed_margin_adj = Column(Float)
    consumer_count = Column(Integer)
    consumer_volume = Column(Float)
    consumer_sales_inc_vat = Column(Float)
    consumer_sales_ex_vat = Column(Float)
    consumer_net_margin_cost = Column(Float)
    consumer_bunker_commission = Column(Float)
    consumer_fixed_margin_adj = Column(Float)
    created_at = Column(DateTime)
    updated_at = Column(DateTime)
    retail_cost_of_stock = Column(Float)
    retail_sales_ex_vat_for_margin = Column(Float)
    retail_cost_of_stock_for_margin = Column(Float)
    retail_volume_for_margin = Column(Float)
    retail_net_margin_cost_for_margin = Column(Float)
    retail_fixed_margin_adj_for_margin = Column(Float)