from pydantic import BaseModel
from datetime import datetime

class DailyBlocks(BaseModel):
    id: int
    company_id: int
    station_id: int
    fuel_grade_id: int
    tank_id: int
    start_time: datetime
    end_time: datetime
    reporting_day: str
    delivered_volume: float
    delivered_cost: float
    fuel_level: float
    fifo_blended_cost: float
    total_count: int
    total_volume: float
    total_sales_inc_vat: float
    total_sales_ex_vat: float
    total_net_margin_cost: float
    total_bunker_commission: float
    total_fixed_margin_adj: float
    fuel_card_count: int
    fuel_card_volume: float
    fuel_card_sales_inc_vat: float
    fuel_card_sales_ex_vat: float
    fuel_card_net_margin_cost: float
    fuel_card_bunker_commission: float
    fuel_card_fixed_margin_adj: float
    bunkered_count: int
    bunkered_volume: float
    bunkered_sales_inc_vat: float
    bunkered_sales_ex_vat: float
    bunkered_net_margin_cost: float
    bunkered_bunker_commission: float
    bunkered_fixed_margin_adj: float
    retail_count: int
    retail_volume: float
    retail_sales_inc_vat: float
    retail_sales_ex_vat: float
    retail_net_margin_cost: float
    retail_bunker_commission: float
    retail_fixed_margin_adj: float
    consumer_count: int
    consumer_volume: float
    consumer_sales_inc_vat: float
    consumer_sales_ex_vat: float
    consumer_net_margin_cost: float
    consumer_bunker_commission: float
    consumer_fixed_margin_adj: float
    created_at: datetime
    updated_at: datetime
    retail_cost_of_stock: float
    retail_sales_ex_vat_for_margin: float
    retail_cost_of_stock_for_margin: float
    retail_volume_for_margin: float
    retail_net_margin_cost_for_margin: float
    retail_fixed_margin_adj_for_margin: float